<?php

namespace AppBundle\Repository;

/**
 * BoxProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoxProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBoxProducts($box)
    {
        return $this->createQueryBuilder('bp')
            ->join('bp.product', 'p')
            ->select('p, bp')
            ->where('bp.box = :box')->setParameter('box', $box)
            ->getQuery()
            ->getResult();
    }
}
