<?php

namespace AppBundle\Repository;

/**
 * BoxProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoxProductRepository extends \Doctrine\ORM\EntityRepository
{
}
