<?php

namespace AppBundle\Repository;

/**
 * BoxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoxRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBoxProducts($box_id)
    {
        return $this->createQueryBuilder('b')
            ->join('b.boxProduct', 'bp')
            ->join('bp.product', 'p')
            ->select('b, bp')
            ->where('b.id = :box_id')->setParameter('box_id', $box_id)
            ->getQuery()
            ->getResult();
    }

    public function findAchatBoxes()
    {
        return $this->createQueryBuilder('b')
            ->where('b.state != :created_state')
            ->setParameter('created_state', 'created')
            ->getQuery()
            ->getResult();
    }
}
