<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastNotification(User $user)
    {
        return $this->createQueryBuilder('n')
                ->where('n.to = :user')->setParameter('user', $user)
                ->orderBy('n.id', 'DESC')
                ->getQuery()
                ->getResult();
    }
}
