# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: _username
        in_memory:
            memory: ~

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path : login
                check_path : login

            logout:
                path: logout
                target: login

            provider: db_provider

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/supplier, roles: ROLE_ACHAT }
        - { path: ^/box, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_MARKETING: ROLE_ADMIN
        ROLE_ACHAT: ROLE_ADMIN
        ROLE_SUPPLIER: ROLE_ADMIN
        ROLE_SUPERADMIN: [ROLE_SUPPLIER, ROLE_ALLOWED_TO_SWITCH]